USE [Francisco]
GO

/****** Object:  Table [dbo].[usuario]    Script Date: 2/13/2022 10:32:49 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[usuario](
	[NOMBRE] [varchar](20) NOT NULL,
	[CONTRASEÒA] [int] NOT NULL,
	[id] [int] IDENTITY(1,1) NOT NULL,
	[SELECCIONAR] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


